
INSERT IGNORE INTO body_part (body_part_code, body_name, side, direction) VALUES
('B_NECK', '뒷목', NULL, 'BACK'),
('B_MID_BACK_L', '등 중부', 'LEFT', 'BACK'),
('B_MID_BACK_R', '등 중부', 'RIGHT', 'BACK'),
('B_LOWER_BACK_L', '허리', 'LEFT', 'BACK'),
('B_LOWER_BACK_R', '허리', 'RIGHT', 'BACK'),
('B_SHOULDER_L', '어깨', 'LEFT', 'BACK'),
('B_SHOULDER_R', '어깨', 'RIGHT', 'BACK'),
('B_UPPER_ARM_L', '위팔(삼두)', 'LEFT', 'BACK'),
('B_UPPER_ARM_R', '위팔(삼두)', 'RIGHT', 'BACK'),
('B_GLUTES_L', '엉덩이', 'LEFT', 'BACK'),
('B_GLUTES_R', '엉덩이', 'RIGHT', 'BACK'),
('B_THIGH_L', '허벅지 뒤', 'LEFT', 'BACK'),
('B_THIGH_R', '허벅지 뒤', 'RIGHT', 'BACK'),
('B_KNEE_L', '오금', 'LEFT', 'BACK'),
('B_KNEE_R', '오금', 'RIGHT', 'BACK'),
('B_CALF_L', '종아리', 'LEFT', 'BACK'),
('B_CALF_R', '종아리', 'RIGHT', 'BACK'),
('F_NECK', '목 앞면', NULL, 'FRONT'),
('F_SHOULDER_L', '어깨', 'LEFT', 'FRONT'),
('F_SHOULDER_R', '어깨', 'RIGHT', 'FRONT'),
('F_CHEST_L', '가슴', 'LEFT', 'FRONT'),
('F_CHEST_R', '가슴', 'RIGHT', 'FRONT'),
('F_ABS', '복부', NULL, 'FRONT'),
('F_OBLIQUE_L', '옆구리', 'LEFT', 'FRONT'),
('F_OBLIQUE_R', '옆구리', 'RIGHT', 'FRONT'),
('F_UPPER_ARM_L', '위팔(이두)', 'LEFT', 'FRONT'),
('F_UPPER_ARM_R', '위팔(이두)', 'RIGHT', 'FRONT'),
('F_PELVIS_L', '서혜부/골반', 'LEFT', 'FRONT'),
('F_PELVIS_R', '서혜부/골반', 'RIGHT', 'FRONT'),
('F_THIGH_L', '허벅지 앞', 'LEFT', 'FRONT'),
('F_THIGH_R', '허벅지 앞', 'RIGHT', 'FRONT'),
('F_KNEE_L', '무릎 앞', 'LEFT', 'FRONT'),
('F_KNEE_R', '무릎 앞', 'RIGHT', 'FRONT'),
('F_SHIN_L', '정강이', 'LEFT', 'FRONT'),
('F_SHIN_R', '정강이', 'RIGHT', 'FRONT'),
('UPPER_BACK_L', '등 상부', 'LEFT', NULL),
('UPPER_BACK_R', '등 상부', 'RIGHT', NULL),
('HEAD', '머리', NULL, NULL),
('FOOT_L', '발', 'LEFT', NULL),
('FOOT_R', '발', 'RIGHT', NULL),
('LOWER_ARM_L', '아래팔', 'LEFT', NULL),
('LOWER_ARM_R', '아래팔', 'RIGHT', NULL);
